import matplotlib.pyplot as plt
import networkx as nx
G = nx.Graph()
G.add_node("Basel",h=204)
G.add_node('Bern', h=247)
G.add_node('Frankfurt',h=215)
G.add_node("Karlsruhe",h=137)
G.add_node('Linz', h=318)
G.add_node('Mannheim', h=164)
G.add_node('Munchen', h=120)
G.add_node('Memmingen', h=47)
G.add_node('Nurnberg', h=132)
G.add_node('Passau', h=257)
G.add_node('Rosenheim',h=168)
G.add_node("Stuttgart", h=75)
G.add_node('Salzburg', h=236)
G.add_node('Wurzburg', h=153)
G.add_node('Zurich', h=157)
G.add_node('Ulm', h=0)
G.add_edge('Frankfurt', 'Wurzburg',weight=111)
G.add_edge('Frankfurt', 'Mannheim', weight=85)
G.add_edge('Wurzburg', 'Nurnberg', weight=104)
G.add_edge('Wurzburg', 'Stuttgart',weight=140)
G.add_edge('Wurzburg', 'Ulm', weight=183)
G.add_edge('Mannheim', 'Nurnberg', weight=230)
G.add_edge('Mannheim', 'Karlsruhe', weight=67)
G.add_edge('Karlsruhe', 'Basel', weight=191)
G.add_edge('Karlsruhe', 'Stuttgart',weight=64)
G.add_edge('Nurnberg', 'Ulm', weight=171)
G.add_edge('Nurnberg', 'Munchen', weight=170)
G.add_edge('Nurnberg', 'Passau', weight=220)
G.add_edge('Stuttgart', 'Ulm', weight=107)
G.add_edge('Basel', 'Bern', weight=91)
G.add_edge('Basel', 'Zurich', weight=85)
G.add_edge('Bern', 'Zurich', weight=120)
G.add_edge('Zurich', 'Memmingen', weight=184)
G.add_edge('Memmingen', 'Ulm', weight=55)
G.add_edge('Memmingen', 'Munchen', weight=115)
G.add_edge('Munchen', 'Ulm', weight=123)
G.add_edge('Munchen', 'Passau', weight=189)
G.add_edge('Munchen', 'Rosenheim', weight=59)
G.add_edge('Rosenheim', 'Salzburg', weight=81)
G.add_edge('Passau', 'Linz', weight=102)
G.add_edge('Salzburg', 'Linz', weight=126)
nx.draw(G, pos=nx.kamada_kawai_layout(G), with_labels='True',node_size=1600, font_size=7, font_color='white')
labels = nx.get_edge_attributes(G, 'weight') 
heuristics = nx.get_node_attributes(G,name="h")
plt.figure(1)
nx.draw_networkx_edge_labels(G, pos=nx.kamada_kawai_layout(G),edge_labels=labels)
nx.draw_networkx_labels(G, pos=nx.kamada_kawai_layout(G), font_size=7,labels=heuristics, font_color="red", verticalalignment='baseline')
plt.show()